name: Deploy to Azure App Service

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Ensure this matches your Azure runtime

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NEW }}

      - name: Build and Push Docker Image
        run: |
          docker build -t aigentychatbot.azurecr.io/aigenty-chatbot:latest .
          echo "1jPA+g/pxi0qkmY6UyuKzuDgOk6dwgZpPT+vVwzY+z+ACRCcQ+av" | docker login aigentychatbot.azurecr.io -u aigentychatbot --password-stdin
          docker push aigentychatbot.azurecr.io/aigenty-chatbot:latest

      - name: Configure Azure Web App
        run: |
          az webapp config container set --name aigenty-chatbot --resource-group aigenty-portal --docker-custom-image-name aigentychatbot.azurecr.io/aigenty-chatbot:latest
          az webapp config set --resource-group aigenty-portal --name aigenty-chatbot --startup-file ". antenv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000"

      - name: Logout from Azure
        run: az logout
