name: Deploy to Azure App Service

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: aigentychatbot.azurecr.io
          username: "aigentychatbot" # Replace with the retrieved username
          password: "wf3z4075boJeKV6AMHK+5lIqxIXWSJCCBJ4ZqGZVxP+ACRAIdhJ+" # Replace with the retrieved primary password

      - name: Build and push Docker image
        run: |
          docker build -t aigentychatbot.azurecr.io/aigenty-chatbot:latest .
          docker push aigentychatbot.azurecr.io/aigenty-chatbot:latest

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NEW }}

      - name: "Configure Web App"
        run: |
          az webapp config set --resource-group aigenty-portal --name aigenty-chatbot --linux-fx-version "PYTHON|3.12"
          az webapp config set --resource-group aigenty-portal --name aigenty-chatbot --startup-file "uvicorn app.main:app --host 0.0.0.0 --port 8000"
          az webapp config container set --name aigenty-chatbot --resource-group aigenty-portal --container-image-name aigentychatbot.azurecr.io/aigenty-chatbot:latest

      - name: Logout from Azure
        run: az logout
